/** Auto-generated by scripts/generate-content-registry.py */
import type { LanguageCode } from "./language-registry";
import type { SiteContent } from "./types";

import { contentHu } from "./content/hu";
import { contentEn } from "./content/en";
import { contentDe } from "./content/de";

export const contentByLocale: Partial<Record<LanguageCode, SiteContent>> = {
  hu: contentHu,
  en: contentEn,
  de: contentDe,
};
