#!/usr/bin/env python3
"""Generate src/lib/i18n/content-registry.ts from locale content files."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "src/lib/i18n/content"
OUT = ROOT / "src/lib/i18n/content-registry.ts"

OFFICIAL = [
    "hu", "en", "de", "ro", "sk", "pl", "cs", "bg", "hr", "sr", "sl", "et", "lv", "lt",
    "fi", "sv", "da", "nb", "nl", "fr", "es", "pt", "it", "el", "tr", "uk", "ru", "sq",
    "mk", "bs", "be", "ga", "mt", "is", "ar",
]


def symbol(locale: str, kind: str) -> str:
    if locale == "nb":
        return f"{kind}Nb"
    return kind + locale[:1].upper() + locale[1:]


def main() -> None:
    locales = [code for code in OFFICIAL if (CONTENT / f"{code}.ts").exists() or code in {"hu", "en"}]
    imports = []
    entries = []
    for code in locales:
        if code == "hu":
            imports.append('import { contentHu } from "./content/hu";')
            entries.append('  hu: contentHu,')
        elif code == "en":
            imports.append('import { contentEn } from "./content/en";')
            entries.append('  en: contentEn,')
        else:
            name = symbol(code, "content")
            imports.append(f'import {{ {name} }} from "./content/{code}";')
            entries.append(f"  {code}: {name},")

    text = "\n".join([
        "/** Auto-generated by scripts/generate-content-registry.py */",
        'import type { LanguageCode } from "./language-registry";',
        'import type { SiteContent } from "./types";',
        "",
        *imports,
        "",
        "export const contentByLocale: Partial<Record<LanguageCode, SiteContent>> = {",
        *entries,
        "};",
        "",
    ])
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT} ({len(locales)} locales)")


if __name__ == "__main__":
    main()
