/** Auto-generated by scripts/generate-content-registry.py */
import type { LanguageCode } from "./language-registry";
import type { SiteContent } from "./types";

import { contentHu } from "./content/hu";
import { contentEn } from "./content/en";
import { contentDe } from "./content/de";
import { contentRo } from "./content/ro";
import { contentSk } from "./content/sk";
import { contentPl } from "./content/pl";
import { contentCs } from "./content/cs";
import { contentBg } from "./content/bg";
import { contentHr } from "./content/hr";
import { contentSr } from "./content/sr";
import { contentSl } from "./content/sl";
import { contentEt } from "./content/et";
import { contentLv } from "./content/lv";
import { contentLt } from "./content/lt";
import { contentFi } from "./content/fi";
import { contentSv } from "./content/sv";
import { contentDa } from "./content/da";
import { contentNb } from "./content/nb";
import { contentNl } from "./content/nl";
import { contentFr } from "./content/fr";
import { contentEs } from "./content/es";
import { contentPt } from "./content/pt";
import { contentIt } from "./content/it";
import { contentEl } from "./content/el";
import { contentTr } from "./content/tr";
import { contentUk } from "./content/uk";
import { contentRu } from "./content/ru";
import { contentSq } from "./content/sq";
import { contentMk } from "./content/mk";
import { contentBs } from "./content/bs";
import { contentBe } from "./content/be";
import { contentGa } from "./content/ga";
import { contentMt } from "./content/mt";
import { contentIs } from "./content/is";
import { contentAr } from "./content/ar";

export const contentByLocale: Record<LanguageCode, SiteContent> = {
  hu: contentHu,
  en: contentEn,
  de: contentDe,
  ro: contentRo,
  sk: contentSk,
  pl: contentPl,
  cs: contentCs,
  bg: contentBg,
  hr: contentHr,
  sr: contentSr,
  sl: contentSl,
  et: contentEt,
  lv: contentLv,
  lt: contentLt,
  fi: contentFi,
  sv: contentSv,
  da: contentDa,
  nb: contentNb,
  nl: contentNl,
  fr: contentFr,
  es: contentEs,
  pt: contentPt,
  it: contentIt,
  el: contentEl,
  tr: contentTr,
  uk: contentUk,
  ru: contentRu,
  sq: contentSq,
  mk: contentMk,
  bs: contentBs,
  be: contentBe,
  ga: contentGa,
  mt: contentMt,
  is: contentIs,
  ar: contentAr,
} as Record<LanguageCode, SiteContent>;
